mutation AddToCart($variantId: String!, $quantity: Int!) {
  addCartItem(variantId: $variantId, quantity: $quantity) {
    ... on MutationAddCartItemSuccess {
      data {
        id
      }
    }
    ... on ArgumentError {
      fieldErrors {
        message
        path
      }
    }
    ... on LogicalError {
      message
    }
  }
}
