mutation CreateMyOrder(
  $cartItemIDs: [String!]!
  $payments: [PaymentInput!]!
  $status: String!
) {
  createMyOrder(
    cartItemIDs: $cartItemIDs
    payments: $payments
    status: $status
  ) {
    ... on MutationCreateMyOrderSuccess {
      data {
        id
      }
    }
    ... on ArgumentError {
      fieldErrors {
        message
        path
      }
    }
    ... on LogicalError {
      message
    }
  }
}
