query GetCategoriesWithProducts(
  $categoryLimit: Int
  $categoryOffset: Int
  $productLimit: Int
  $productOffset: Int
) {
  categories(limit: $categoryLimit, offset: $categoryOffset) {
    description
    id
    name
    products(limit: $productLimit, offset: $productOffset) {
      description
      id
      labelPrice
      name
      variants {
        id
        title
        price
        image {
          id
          source
        }
      }
    }
  }
}
