query GetMyOrders($limit: Int, $offset: Int) {
  myOrders(limit: $limit, offset: $offset) {
    id
    status
    items {
      id
      quantity
      productVariant {
        id
        title
        price
        product {
          id
          name
          labelPrice
        }
      }
    }
  }
}
