query GetOrder($id: String!) {
  order(id: $id) {
    id
    status
    items {
      id
      quantity
      productVariant {
        id
        title
        price
        product {
          id
          name
          labelPrice
        }
      }
    }
  }
}
