query GetProducts($limit: Int, $offset: Int) {
  products(limit: $limit, offset: $offset) {
    id
    name
    description
    labelPrice
    variants {
      id
      image {
        id
        source
        position
      }
      title
      price
    }
  }
}
