query GetProductsByCategoryId(
  $categoryId: String!
  $productLimit: Int
  $productOffset: Int
) {
  category(id: $categoryId) {
    id
    name
    description
    products(limit: $productLimit, offset: $productOffset) {
      id
      name
      labelPrice
      description
      variants {
        id
        title
        price
        image {
          id
          source
          position
        }
      }
    }
  }
}
