mutation RemoveCartItem($id: String!) {
  removeCartItem(id: $id) {
    ... on MutationRemoveCartItemSuccess {
      data {
        id
      }
    }
    ... on ArgumentError {
      fieldErrors {
        message
        path
      }
    }
    ... on LogicalError {
      message
    }
  }
}
