mutation UpdateCartItem($id: String!, $quantity: Int!) {
  updateCartItem(id: $id, quantity: $quantity) {
    ... on MutationUpdateCartItemSuccess {
      data {
        id
      }
    }
    ... on ArgumentError {
      fieldErrors {
        message
        path
      }
    }
    ... on LogicalError {
      message
    }
  }
}
